version: '3.8'

services:
  db:
    image: postgres:15
    container_name: monee-flow-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: monee-flow-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      - db

volumes:
  pgdata:
