version: '3.8'

services:
  db:
    image: postgres:15
    container_name: monee-flow-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    container_name: monee-flow-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./jobs:/app/jobs
      - ./.env:/app/.env
      - ./tmp_data:/app/tmp_data
    environment:
      - UVICORN_OPTIONS=--reload
    depends_on:
      - db

volumes:
  pgdata:
