"""init tables

Revision ID: 12ab2d1a017a
Revises: 
Create Date: 2026-05-07 20:50:02.887670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ab2d1a017a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_old_2025')
    op.drop_table('categories')
    op.alter_column('exchange_rates', 'as_of_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='UTC date derived from source_ts. Represents the day this rate was published.',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'base_currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               comment=None,
               existing_comment='Base currency code (ISO 4217).',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'quote_currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               comment=None,
               existing_comment='Quote currency code (ISO 4217).',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'rate',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment=None,
               existing_comment='Exchange rate',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'source',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='External data source providing the rate.',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'source_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Publication time of the rates from the source (converted from UNIX time).',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation time.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exchange_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row last update time.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_exchange_rates_day_pair'), table_name='exchange_rates')
    op.drop_index(op.f('idx_exchange_rates_lookup'), table_name='exchange_rates')
    op.drop_index(op.f('ux_exchange_rates_day_pair_source'), table_name='exchange_rates')
    op.create_unique_constraint('ux_exchange_rates_day_pair', 'exchange_rates', ['as_of_date', 'base_currency', 'quote_currency'])
    op.drop_table_comment(
        'exchange_rates',
        existing_comment='Daily exchange rate snapshots for currency conversion.',
        schema=None
    )
    op.alter_column('global_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_rules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('unique_norm_desc'), 'global_rules', type_='unique')
    op.drop_constraint(op.f('uq_global_rules_norm_desc'), 'global_rules', type_='unique')
    op.create_index(op.f('ix_global_rules_id'), 'global_rules', ['id'], unique=False)
    op.alter_column('statements', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.alter_column('statements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('statements', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.alter_column('system_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_system_categories_id'), 'system_categories', ['id'], unique=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False)
    op.drop_constraint(op.f('uq_transaction_statement_source'), 'transactions', type_='unique')
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    op.drop_column('transactions', 'note')
    op.drop_column('transactions', 'source_index')
    op.alter_column('user_categories', 'is_del',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_categories_id'), 'user_categories', ['id'], unique=False)
    op.create_index(op.f('ix_user_categories_user_id'), 'user_categories', ['user_id'], unique=False)
    op.alter_column('user_sys_category_prefs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_sys_category_prefs', 'created_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sys_category_prefs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(precision=0),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_user_enabled', 'user_sys_category_prefs', ['user_id', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_user_sys_category_prefs_user_id'), 'user_sys_category_prefs', ['user_id'], unique=False)
    op.alter_column('users', 'default_display_currency',
               existing_type=sa.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'default_display_currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.drop_index(op.f('ix_user_sys_category_prefs_user_id'), table_name='user_sys_category_prefs')
    op.drop_index('idx_user_enabled', table_name='user_sys_category_prefs')
    op.alter_column('user_sys_category_prefs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sys_category_prefs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_sys_category_prefs', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_user_categories_user_id'), table_name='user_categories')
    op.drop_index(op.f('ix_user_categories_id'), table_name='user_categories')
    op.alter_column('user_categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_categories', 'is_del',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('transactions', sa.Column('source_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('note', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.create_unique_constraint(op.f('uq_transaction_statement_source'), 'transactions', ['statement_id', 'source_index'], postgresql_nulls_not_distinct=False)
    op.alter_column('transactions', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False)
    op.drop_index(op.f('ix_system_categories_id'), table_name='system_categories')
    op.alter_column('system_categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('system_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.alter_column('statements', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('statements', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('statements', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.drop_index(op.f('ix_global_rules_id'), table_name='global_rules')
    op.create_unique_constraint(op.f('uq_global_rules_norm_desc'), 'global_rules', ['norm_desc'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('unique_norm_desc'), 'global_rules', ['norm_desc'], postgresql_nulls_not_distinct=False)
    op.alter_column('global_rules', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('global_rules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(precision=0),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'exchange_rates',
        'Daily exchange rate snapshots for currency conversion.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint('ux_exchange_rates_day_pair', 'exchange_rates', type_='unique')
    op.create_index(op.f('ux_exchange_rates_day_pair_source'), 'exchange_rates', ['as_of_date', 'base_currency', 'quote_currency', 'source'], unique=True)
    op.create_index(op.f('idx_exchange_rates_lookup'), 'exchange_rates', ['base_currency', 'source', 'quote_currency', 'as_of_date'], unique=False)
    op.create_index(op.f('idx_exchange_rates_day_pair'), 'exchange_rates', ['as_of_date', 'base_currency', 'quote_currency'], unique=False)
    op.alter_column('exchange_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row last update time.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exchange_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation time.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exchange_rates', 'source_ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Publication time of the rates from the source (converted from UNIX time).',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'source',
               existing_type=sa.VARCHAR(length=100),
               comment='External data source providing the rate.',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'rate',
               existing_type=sa.NUMERIC(precision=18, scale=8),
               comment='Exchange rate',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'quote_currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               comment='Quote currency code (ISO 4217).',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'base_currency',
               existing_type=sa.String(length=3),
               type_=sa.CHAR(length=3),
               comment='Base currency code (ISO 4217).',
               existing_nullable=False)
    op.alter_column('exchange_rates', 'as_of_date',
               existing_type=sa.DATE(),
               comment='UTC date derived from source_ts. Represents the day this rate was published.',
               existing_nullable=False)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_table('transactions_old_2025',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), server_default=sa.text("'1970-01-01'::date"), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('statement_id', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('status = ANY (ARRAY[1, 2])', name=op.f('transactions_status_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('transactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    # ### end Alembic commands ###
