"""init tables

Revision ID: 7b20758b6540
Revises: 
Create Date: 2026-05-07 21:11:41.318194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b20758b6540'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("base_currency ~ '^[A-Z]{3}$'", name='chk_base_currency_iso4217'),
    sa.CheckConstraint("quote_currency ~ '^[A-Z]{3}$'", name='chk_quote_currency_iso4217'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('as_of_date', 'base_currency', 'quote_currency', name='ux_exchange_rates_day_pair')
    )
    op.create_table('global_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('norm_desc', sa.Text(), server_default='', nullable=False),
    sa.Column('category_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('category_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_rules_id'), 'global_rules', ['id'], unique=False)
    op.create_table('system_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('parent_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_categories_id'), 'system_categories', ['id'], unique=False)
    op.create_table('user_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('is_del', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_categories_id'), 'user_categories', ['id'], unique=False)
    op.create_index(op.f('ix_user_categories_user_id'), 'user_categories', ['user_id'], unique=False)
    op.create_table('user_sys_category_prefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_enabled', 'user_sys_category_prefs', ['user_id', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_user_sys_category_prefs_user_id'), 'user_sys_category_prefs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False),
    sa.Column('default_display_currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=False),
    sa.Column('end_time', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='chk_currency_iso4217'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_statements_user_id', 'statements', ['user_id'], unique=False)
    op.create_index(op.f('ix_statements_user_id'), 'statements', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tx_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='chk_currency_iso4217'),
    sa.CheckConstraint('status IN (1,2)', name='chk_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transactions_user_currency_amount', 'transactions', ['user_id', 'currency', 'amount'], unique=False)
    op.create_index('idx_transactions_user_currency_txdate', 'transactions', ['user_id', 'currency', 'tx_date'], unique=False)
    op.create_index('idx_transactions_user_txdate', 'transactions', ['user_id', 'tx_date'], unique=False)
    op.create_index(op.f('ix_transactions_statement_id'), 'transactions', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_statement_id'), table_name='transactions')
    op.drop_index('idx_transactions_user_txdate', table_name='transactions')
    op.drop_index('idx_transactions_user_currency_txdate', table_name='transactions')
    op.drop_index('idx_transactions_user_currency_amount', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_statements_user_id'), table_name='statements')
    op.drop_index('idx_statements_user_id', table_name='statements')
    op.drop_table('statements')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_sys_category_prefs_user_id'), table_name='user_sys_category_prefs')
    op.drop_index('idx_user_enabled', table_name='user_sys_category_prefs')
    op.drop_table('user_sys_category_prefs')
    op.drop_index(op.f('ix_user_categories_user_id'), table_name='user_categories')
    op.drop_index(op.f('ix_user_categories_id'), table_name='user_categories')
    op.drop_table('user_categories')
    op.drop_index(op.f('ix_system_categories_id'), table_name='system_categories')
    op.drop_table('system_categories')
    op.drop_index(op.f('ix_global_rules_id'), table_name='global_rules')
    op.drop_table('global_rules')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
